from sqlalchemy.orm import Session
from app.models.domain.user import User
from app.models.schemas.user import UserCreate

class UserRepository:
    def __init__(self, db_session):
        self.db = db_session

    def get_by_email(self, email: str):
        """Finds user by email"""
        return self.db.query(User).filter(User.email == email).first()

    def get_by_spotify_id(self, spotify_id: str):
        """Retrieves a user by primary key"""
        from app.models.domain.spotify import SpotifyAccount
        account = self.db.query(SpotifyAccount).filter_by(spotify_user_id=spotify_id).first()
        return account.user if account else None

    def create(self, email: str):
        """
        Creates new user with autogenerated ID
        Args:
            email: User's email address (unique)            
        Returns:
            Persisted User entity
        """
        user = User(email=email)
        self.db.add(user)
        self.db.commit()
        self.db.refresh(user)  
        return user

    def get_or_create(self, email: str):
        """
        Atomic get-or-create operation
        Returns existing user if found, otherwise creates new
        """
        user = self.get_by_email(email)
        if not user:
            user = self.create(email)
            self.db.commit()
        return user