name: Daily Spotify Sync                # Workflow name

on:
  schedule:
    - cron: '5 0 * * *'                 # The daily execution takes place at 00:05 UTC
  workflow_dispatch:                    # Allows manual execution from the GitHub interface

jobs:
  daily-sync:                           # Define a job called "daily-sync" 
    runs-on: ubuntu-latest              # Run on the latest available Ubuntu
    steps:                              # Steps that the job will execute in sequence       
      - uses: actions/checkout@v2       # Step 1: Checkout the code
      
      - name: Set up Python             # Step 2: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies      # Step 3: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt          
          
      - name: Run Daily Sync            # Step 4: Run the script   
        env:
          CLOUDAMQP_URL: ${{ secrets.CLOUDAMQP_URL }}          
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          LASTFM_API_KEY : ${{ secrets.LASTFM_API_KEY }}
          LASTFM_API_SECRET : ${{ secrets.LASTFM_API_SECRET }}
          FLASK_ENV: ${{ secrets.FLASK_ENV }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python -c "from app.workers.task_dispatcher import dispatch_daily_task; dispatch_daily_task()"